# Generated by Django 5.2.15 on 2026-06-08 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do bairro')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da cidade')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Status do animal')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=50, verbose_name='Nome da espécie')),
                ('raca', models.CharField(max_length=50, verbose_name='Nome da raça')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, verbose_name='Sigla da Unidade da Federação')),
            ],
            options={
                'verbose_name': 'Unidade da Federação',
                'verbose_name_plural': 'Unidades da Federação',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do animal')),
                ('tamanho', models.CharField(max_length=4, verbose_name='Tamanho(cm) do animal')),
                ('idade', models.IntegerField(verbose_name='Idade do animal')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bairro', verbose_name='Bairro frequentemente visto')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.status', verbose_name='Status do animal')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo', verbose_name='Tipo do animal')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.AddField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade do bairro'),
        ),
        migrations.CreateModel(
            name='FotoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_foto', models.CharField(max_length=100, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('descricao', models.TextField(verbose_name='Descrição da foto')),
                ('data_upload', models.DateField(verbose_name='data de upload')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.animal', verbose_name='Animal da foto')),
            ],
            options={
                'verbose_name': 'Foto do animal',
                'verbose_name_plural': 'Fotos dos animais',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uf', verbose_name='UF'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do usuário')),
                ('email', models.CharField(max_length=50, verbose_name='e-mail')),
                ('senha', models.CharField(max_length=50, verbose_name='senha')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('numero', models.CharField(max_length=11, verbose_name='Número de telefone')),
                ('data', models.DateField(verbose_name='data de nascimento')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade do usuário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrelas', models.IntegerField(verbose_name='Quantidade de estrelas')),
                ('comentario', models.TextField(verbose_name='comentário')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Nome de usuário')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da vacina')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.animal', verbose_name='Animal vacinado')),
            ],
            options={
                'verbose_name': 'Vacina',
                'verbose_name_plural': 'Vacinas',
            },
        ),
        migrations.CreateModel(
            name='AnimalporVacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.animal', verbose_name='Animal')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vacina', verbose_name='Vacina')),
            ],
            options={
                'verbose_name': 'Animal por vacina',
                'verbose_name_plural': 'Animais por vacinas',
            },
        ),
    ]
