# Generated by Django 5.2.15 on 2026-06-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacina',
            name='animal',
        ),
        migrations.AlterField(
            model_name='animal',
            name='tamanho',
            field=models.CharField(max_length=4, verbose_name='Altura(cm) do animal'),
        ),
    ]
